/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IM.Javalin.Server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class IMSeverTest {
    @Test void testAFunction() {
        //FESever classUnderTest = new FESever();

    }
}
