/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DC.Javalin.Server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DCServerTest {
    // I have no clue how to unit test a class that only has a main()
    // we'll come back to this.
}
